language: node_js

before_deploy:
  - npm install hexo-cli -g
  - npm install
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
