language: node_js
node_js: "node"

before_deploy:
  - eval "$(curl -sL https://raw.githubusercontent.com/ApolloZhu/script/master/hexo/generate)"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  on:
    branch: source
