# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: AZ
subtitle: 'Apollonian Blog'
description: 'Beyond the sky, into the nyaamament'
keywords:
author: Apollo Zhu
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ApolloZhu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - baidu_verify_4AmFb3PnNc.html
  - googlea5c915d48bc4b68b.html
  - swift-educational-notes/index.html
  - Developing-iOS-11-Apps-with-Swift/index.html
  - Developing-iOS-10-Apps-with-Swift/index.html
  
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
### RSS
plugin:
- hexo-generator-feed
#### Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 0
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

### Local Search by hexo-generator-searchdb
search:
 path: search.xml
 field: post
 format: html
 limit: 10000

# hexo-helper-live2d
live2d:
  enable: true
  model:
    use: live2d-widget-model-hijiki
  display:
    width: 200
    height: 300
  mobile:
    show: false
  react:
    opacityDefault: 1
  dev:
    border: false

aplayer:
  meting: true

# NeedMoreShare2
# Dependencies: https://github.com/theme-next/theme-next-needmoreshare2
# For more information: https://github.com/revir/need-more-share2
# iconStyle: default | box
# boxForm: horizontal | vertical
# position: top / middle / bottom + Left / Center / Right
# networks:
# Weibo | Wechat | Douban | QQZone | Twitter | Facebook | Linkedin | Mailto | Reddit | Delicious | StumbleUpon | Pinterest
# GooglePlus | Tumblr | GoogleBookmarks | Newsvine | Evernote | Friendfeed | Vkontakte | Odnoklassniki | Mailru
needmoreshare:
  enable: true
  cdn:
    js: //cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@1/needsharebutton.min.js
    css: //cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@1/needsharebutton.min.css
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook,
                Linkedin,Mailto,Reddit,Delicious,StumbleUpon,
                Pinterest,GooglePlus,Tumblr,GoogleBookmarks,
                Newsvine,Evernote,Friendfeed,Vkontakte,
                Odnoklassniki,Mailru
  float:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,QQZone,Twitter,Facebook,Mailto

alias:
  2017/08/30/ap-chem-survey/index.html: en/2017/08/30/ap-chem-survey/index.html
  2017/05/02/apcsa-appendix-b/index.html: en/2017/05/02/apcsa-appendix-b/index.html
  2017/08/25/apcsab-survey/index.html: en/2017/08/25/apcsab-survey/index.html
  2018/06/11/computer-science-education/index.html: en/2018/06/11/computer-science-education/index.html
  2018/07/10/cs193c-memes/index.html: en/2018/07/10/cs193c-memes/index.html
  2017/05/24/letter-to-apcsa-students/index.html: en/2017/05/24/letter-to-apcsa-students/index.html
