name: Deploy

on:
  push:
    branches: [ source ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Dependencies
      run: |
        git clone https://github.com/theme-next/theme-next-pace themes/next/source/lib/pace
        npm install
    # https://blog.baoshuo.ren/post/auto-deploy-static-blog/#github-actions
    - name: Fix File Modification Date
      run: |
        git ls-files | while read filepath; do touch -d "$(git log -1 --format='@%ct' $filepath)" "$filepath" && echo "Fixed: $filepath"; done
    - name: Generate
      run: |
        ./node_modules/hexo/bin/hexo clean
        ./node_modules/hexo/bin/hexo generate
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./public
        force_orphan: true
